defmodule Communer.Repo.Migrations.AddPackageVersionAndRepo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:packages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :latest_version, :text
      add :type, :text
      add :url, :text

      add :package_id,
          references(:packages,
            column: :id,
            name: "packages_package_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:package_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :text

      add :package_id,
          references(:packages,
            column: :id,
            name: "package_versions_package_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:package_versions, "package_versions_package_id_fkey")

    drop table(:package_versions)

    drop constraint(:packages, "packages_package_id_fkey")

    drop table(:packages)
  end
end
